name: build

# on:
#   push:
#     branches:
#       - main
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: ls -al && npm run && rm -rf docs/ && npm run build && mv dist docs
      # rm -rf docs/ && npm run build && mv dist docs
