name: build

on: [push]

# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      # - run: |
      #     ls -al
      #     npm i
      #     rm -rf docs/
      #     npm run build
      #     mv dist docs
      #     ls -al
      #     cd docs
      #     ls -a
      #     git status
